flutter_application_path = 'my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


platform :ios, '9.0'
target 'Flutter_iOS' do
  install_all_flutter_pods(flutter_application_path)
end



